# Go cross compiler (xgo): Base cross-compilation layer
# Copyright (c) 2014 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

FROM sillydong/xgo-centos-1.10.2

MAINTAINER Péter Szilágyi <peterke@gmail.com>
